version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/finance_tracker
      - PORT=5000
      - ACCESS_TOKEN_EXPIRY=1d
      - ACCESS_TOKEN_SECRET=1234
      - CORS_ORIGIN=http://localhost:5173
      
  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: finance_tracker

volumes:
  mongodb_data:
    driver: local